---
title: 'Predicting Premature Death Based on Health and Socio-economic Factors'
author: 'Team Illinois: Data Analysis Project Report'
date: '08/07/2020'
output:
  html_document: 
    theme: readable
    toc: yes
  pdf_document: default
urlcolor: cyan
---
***

**Team Illinois Members**

  - Julia Dawson, NETID: TODO
  
  - Joseph Stewart, NETID: TODO
  
  - Saumya Singh, NETID: saumyas2
  
***

```{r setup, include=FALSE}

# Read as packages here
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(dplyr)
library(faraway)
library(lmtest)
library(MASS)
library(knitr)
library(kableExtra)
```

# Introduction


# Methods

## Approach 1

## Approach 2

## Approach 3
```{r}
model_3 = lm(Employed ~ . , data = longley)
```

## Model Diagnostics

```{r}

plot_fitted_resid = function(model, pointcol = "dodgerblue", linecol = "darkorange", title) {
  
  plot(fitted(model), resid(model), col = pointcol, pch = 20, cex = 1.5, xlab = "Fitted", ylab = "Residuals", main = title)
  abline(h = 0, col = linecol, lwd = 2)
}

plot_qq = function(model, pointcol = "dodgerblue", linecol = "darkorange", title) {
  qqnorm(resid(model), main = title, col = pointcol, pch = 20, cex = 1.5)
  qqline(resid(model), col = linecol, lwd = 2)
}

plot_hist_resid = function(model, pointcol = "dodgerblue", linecol = "darkorange", title) {
  hist(resid(model),
       xlab   = "Residuals",
       main   = title,
       col    = pointcol,
       border = linecol,
       breaks = 45)
}

```

**Residuals Plot**
```{r fig.height=8, fig.width=20}
par(mfrow = c(1,3))
plot_fitted_resid(model_3, title="Model 1")
plot_fitted_resid(model_3, title="Model 2")
plot_fitted_resid(model_3, title="Model 3")

```

**Q-Q Plot**
```{r}
par(mfrow = c(1,3))

```




# Results


# Discussion

```{r}

get_bp = function(model) {
  bptest(model)$p.value
  #decide = unname(bptest(model)$p.value < alpha)
  #ifelse(decide, "Reject", "Fail to Reject")
}

get_sw = function(model) {
  shapiro.test(resid(model))$p.value
  #decide = unname(shapiro.test(resid(model))$p.value < alpha)
  #ifelse(decide, "Reject", "Fail to Reject")
}

get_num_params = function(model) {
  length(coef(model))
}

get_loocv_rmse = function(model) {
  sqrt(mean((resid(model) / (1 - hatvalues(model))) ^ 2))
}

get_adj_r2 = function(model) {
  summary(model)$adj.r.squared
}

get_rmse = function(model) {
  sqrt(mean(resid(model) ^ 2))
}

get_AIC = function(model) {
  extractAIC(model)[2]
}

info_1 = list(get_bp(model_3), get_sw(model_3), get_num_params(model_3), 
              get_loocv_rmse(model_3), get_adj_r2(model_3), get_rmse(model_3), get_AIC(model_3))
info_2 = list(get_bp(model_3), get_sw(model_3), get_num_params(model_3), 
              get_loocv_rmse(model_3), get_adj_r2(model_3), get_rmse(model_3), get_AIC(model_3))
info_3 = list(get_bp(model_3), get_sw(model_3), get_num_params(model_3), 
              get_loocv_rmse(model_3), get_adj_r2(model_3), get_rmse(model_3), get_AIC(model_3))

model_info = cbind(info_1, info_2, info_3)

rownames(model_info) = c("BP Test", "Shapiro","No params", "LOOV RMSE", "Adj R2", "RMSE", "AIC")
colnames(model_info) = c("Model 1", "Model 2", "Model 3")
knitr::kable(model_info) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```


# Appendix
